--------------------------------------------------------
-- Archivo creado  - lunes-julio-20-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALTERNATIVAS
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."ALTERNATIVAS" 
   (	"ID_TEST" NUMBER(*,0), 
	"ID_PREG" NUMBER(*,0), 
	"ALTERN" VARCHAR2(1 BYTE), 
	"DESCALTER" VARCHAR2(30 BYTE), 
	"VALORLOGICO" CHAR(1 BYTE), 
	"VALORPORC" NUMBER(*,0), 
	"PREGUNTAS_TESTEVA_IDTEST" NUMBER(*,0), 
	"PREGUNTAS_IDTEST" NUMBER(*,0), 
	"PREGUNTAS_NUMPRE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.ALTERNATIVAS
SET DEFINE OFF;
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','1','A','Test 1 Pregunta1 alterna A','V','50','1','1','1');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','2','A','Test 1 Pregunta2 alterna A','V','50','1','1','2');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','1','A','Test 2 Pregunta1 alterna A','V','50','2','2','1');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','2','A','Test 2 Pregunta2 alterna A','V','50','2','2','2');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','3','A','Test 1 Pregunta3 alterna A','V','50','1','1','3');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','4','A','Test 1 Pregunta4 alterna A','V','50','1','1','4');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','5','A','Test 1 Pregunta5 alterna A','V','50','1','1','5');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','6','A','Test 1 Pregunta6 alterna A','V','50','1','1','6');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','7','A','Test 1 Pregunta7 alterna A','V','50','1','1','7');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','8','A','Test 1 Pregunta8 alterna A','V','50','1','1','8');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','9','A','Test 1 Pregunta9 alterna A','V','50','1','1','9');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','10','A','Test 1 Pregunta10 alterna A','V','50','1','1','10');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','3','A','Test 2 Pregunta3 alterna A','V','50','2','2','3');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','4','A','Test 2 Pregunta4 alterna A','V','50','2','2','4');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','5','A','Test 2 Pregunta5 alterna A','V','50','2','2','5');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','6','A','Test 2 Pregunta6 alterna A','V','50','2','2','6');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','7','A','Test 2 Pregunta7 alterna A','V','50','2','2','7');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','8','A','Test 2 Pregunta8 alterna A','V','50','2','2','8');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','9','A','Test 2 Pregunta9 alterna A','V','50','2','2','9');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','10','A','Test 2 Pregunta10 alterna A','V','50','2','2','10');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','1','B','Test 1 Pregunta1 alterna B','V','25','1','1','1');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','2','B','Test 1 Pregunta2 alterna B','V','25','1','1','2');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','3','B','Test 1 Pregunta3 alterna B','V','25','1','1','3');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','4','B','Test 1 Pregunta4 alterna B','V','25','1','1','4');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','5','B','Test 1 Pregunta5 alterna B','V','25','1','1','5');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','6','B','Test 1 Pregunta6 alterna B','V','25','1','1','6');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','7','B','Test 1 Pregunta7 alterna B','V','25','1','1','7');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','8','B','Test 1 Pregunta8 alterna B','V','25','1','1','8');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','9','B','Test 1 Pregunta9 alterna B','V','25','1','1','9');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','10','B','Test 1 Pregunta10 alterna B','V','25','1','1','10');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','1','B','Test 2 Pregunta1 alterna B','V','25','2','2','1');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','2','B','Test 2 Pregunta2 alterna B','V','25','2','2','2');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','3','B','Test 2 Pregunta3 alterna B','V','25','2','2','3');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','4','B','Test 2 Pregunta4 alterna B','V','25','2','2','4');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','5','B','Test 2 Pregunta5 alterna B','V','25','2','2','5');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','6','B','Test 2 Pregunta6 alterna B','V','25','2','2','6');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','7','B','Test 2 Pregunta7 alterna B','V','25','2','2','7');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','8','B','Test 2 Pregunta8 alterna B','V','25','2','2','8');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','9','B','Test 2 Pregunta9 alterna B','V','25','2','2','9');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','10','B','Test 2 Pregunta10 alterna B','V','25','2','2','10');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','1','C','Test 1 Pregunta1 alterna C','F','0','1','1','1');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','2','C','Test 1 Pregunta2 alterna C','F','0','1','1','2');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','3','C','Test 1 Pregunta3 alterna C','F','0','1','1','3');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','4','C','Test 1 Pregunta4 alterna C','F','0','1','1','4');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','5','C','Test 1 Pregunta5 alterna C','F','0','1','1','5');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','6','C','Test 1 Pregunta6 alterna C','F','0','1','1','6');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','7','C','Test 1 Pregunta7 alterna C','F','0','1','1','7');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','8','C','Test 1 Pregunta8 alterna C','F','0','1','1','8');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','9','C','Test 1 Pregunta9 alterna C','F','0','1','1','9');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','10','C','Test 1 Pregunta10 alterna C','F','0','1','1','10');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','1','C','Test 2 Pregunta1 alterna C','V','25','2','2','1');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','2','C','Test 2 Pregunta2 alterna C','V','25','2','2','2');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','3','C','Test 2 Pregunta3 alterna C','V','25','2','2','3');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','4','C','Test 2 Pregunta4 alterna C','V','25','2','2','4');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','5','C','Test 2 Pregunta5 alterna C','V','25','2','2','5');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','6','C','Test 2 Pregunta6 alterna C','V','25','2','2','6');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','7','C','Test 2 Pregunta7 alterna C','V','25','2','2','7');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','8','C','Test 2 Pregunta8 alterna C','V','25','2','2','8');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','9','C','Test 2 Pregunta9 alterna C','V','25','2','2','9');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','10','C','Test 2 Pregunta10 alterna C','V','25','2','2','10');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','1','D','Test 1 Pregunta1 alterna D','V','25','1','1','1');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','2','D','Test 1 Pregunta2 alterna D','V','25','1','1','2');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','3','D','Test 1 Pregunta3 alterna D','V','25','1','1','3');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','4','D','Test 1 Pregunta4 alterna D','V','25','1','1','4');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','5','D','Test 1 Pregunta5 alterna D','V','25','1','1','5');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','6','D','Test 1 Pregunta6 alterna D','V','25','1','1','6');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','7','D','Test 1 Pregunta7 alterna D','V','25','1','1','7');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','8','D','Test 1 Pregunta8 alterna D','V','25','1','1','8');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','9','D','Test 1 Pregunta9 alterna D','V','25','1','1','9');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('1','10','D','Test 1 Pregunta10 alterna D','V','25','1','1','10');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','1','D','Test 2 Pregunta1 alterna D','F','0','2','2','1');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','2','D','Test 2 Pregunta2 alterna D','F','0','2','2','2');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','3','D','Test 2 Pregunta3 alterna D','F','0','2','2','3');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','4','D','Test 2 Pregunta4 alterna D','F','0','2','2','4');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','5','D','Test 2 Pregunta5 alterna D','F','0','2','2','5');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','6','D','Test 2 Pregunta6 alterna D','F','0','2','2','6');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','7','D','Test 2 Pregunta7 alterna D','F','0','2','2','7');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','8','D','Test 2 Pregunta8 alterna D','F','0','2','2','8');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','9','D','Test 2 Pregunta9 alterna D','F','0','2','2','9');
Insert into TDIGITAL.ALTERNATIVAS (ID_TEST,ID_PREG,ALTERN,DESCALTER,VALORLOGICO,VALORPORC,PREGUNTAS_TESTEVA_IDTEST,PREGUNTAS_IDTEST,PREGUNTAS_NUMPRE) values ('2','10','D','Test 2 Pregunta10 alterna D','F','0','2','2','10');
--------------------------------------------------------
--  DDL for Index ALTERNATIVAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."ALTERNATIVAS_PK" ON "TDIGITAL"."ALTERNATIVAS" ("ID_TEST", "ID_PREG", "ALTERN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ALTERNATIVAS
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."ALTERNATIVAS" ADD CONSTRAINT "ALTERNATIVAS_PK" PRIMARY KEY ("ID_TEST", "ID_PREG", "ALTERN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."ALTERNATIVAS" MODIFY ("PREGUNTAS_NUMPRE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ALTERNATIVAS" MODIFY ("PREGUNTAS_IDTEST" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ALTERNATIVAS" MODIFY ("PREGUNTAS_TESTEVA_IDTEST" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ALTERNATIVAS" MODIFY ("VALORPORC" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ALTERNATIVAS" MODIFY ("VALORLOGICO" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ALTERNATIVAS" MODIFY ("DESCALTER" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ALTERNATIVAS" MODIFY ("ALTERN" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ALTERNATIVAS" MODIFY ("ID_PREG" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ALTERNATIVAS" MODIFY ("ID_TEST" NOT NULL ENABLE);
