--------------------------------------------------------
-- Archivo creado  - lunes-julio-20-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CURSO
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."CURSO" 
   (	"IDCURSO" NUMBER(*,0), 
	"DESCRIP" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.CURSO
SET DEFINE OFF;
Insert into TDIGITAL.CURSO (IDCURSO,DESCRIP) values ('1','Programación Básica en Java');
Insert into TDIGITAL.CURSO (IDCURSO,DESCRIP) values ('2','Lenguaje de Base de Datos');
Insert into TDIGITAL.CURSO (IDCURSO,DESCRIP) values ('3','Programación Android');
--------------------------------------------------------
--  DDL for Index CURSO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."CURSO_PK" ON "TDIGITAL"."CURSO" ("IDCURSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CURSO
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."CURSO" ADD CONSTRAINT "CURSO_PK" PRIMARY KEY ("IDCURSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."CURSO" MODIFY ("DESCRIP" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."CURSO" MODIFY ("IDCURSO" NOT NULL ENABLE);
