--------------------------------------------------------
-- Archivo creado  - lunes-julio-20-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ESTUDIANTE
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."ESTUDIANTE" 
   (	"IDESTU" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDO" VARCHAR2(30 BYTE), 
	"FONO" NUMBER(*,0), 
	"DIRECC" VARCHAR2(30 BYTE), 
	"IDCURSO" NUMBER(*,0), 
	"CURSO_IDCURSO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.ESTUDIANTE
SET DEFINE OFF;
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('1111111111','Juan','Pérez','12458754','La orilla #33','1','1');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('2222222222','Romina','Mena','2929589','El vólcan #56','1','1');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('3333333333','Paz','Solar','56568965','El bosque #455','1','1');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('4444444444','Marco','Segovia','8989569','Los Avellanos #8976','1','1');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('5555555555','Francisca','López','78785896','Volcán #321','1','1');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('6666666666','Manuel','González','78786322','Cristóbal #765','1','1');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('7777777777','José','Román','33345871','El océano #4567','1','1');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('8888888888','Luisa','Tapia','2323581','San Juan 334','1','1');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('9999999999','Maca','Seguel','4545878','El solar #45','1','1');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('1010101010','Paola','González','7979895','La Arbolera #765','1','1');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('1112111111','Elizabhet','Suazo','5656874','La Paz #12','2','2');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('1212121212','Armando','Casas','7878452','Av. España#333','2','2');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('1515151515','Daniel','Salas','7878777','Antillanca #8914','2','2');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('1616161616','Raúl','Robles','5959875','El centro #87','2','2');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('1717171717','Pancho','López','6969875','Av. bulnes #12','2','2');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('1818181818','Oscar','Soto','8989785','El oso #34','2','2');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('1919191919','Felipe','Hermosilla','7878555','La calle #98','2','2');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('2020202020','Omar','Ramos','8999999','El arcoiris #66','2','2');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('1313131313','Eduardo','Aruos','45784555','Av.Bilbao #12','2','2');
Insert into TDIGITAL.ESTUDIANTE (IDESTU,NOMBRE,APELLIDO,FONO,DIRECC,IDCURSO,CURSO_IDCURSO) values ('1414141414','Felipe','Arroz','7878785','El pasaje #45','2','2');
--------------------------------------------------------
--  DDL for Index ESTUDIANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."ESTUDIANTE_PK" ON "TDIGITAL"."ESTUDIANTE" ("IDESTU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_PK" PRIMARY KEY ("IDESTU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."ESTUDIANTE" MODIFY ("CURSO_IDCURSO" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ESTUDIANTE" MODIFY ("IDCURSO" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ESTUDIANTE" MODIFY ("DIRECC" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ESTUDIANTE" MODIFY ("FONO" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ESTUDIANTE" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ESTUDIANTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."ESTUDIANTE" MODIFY ("IDESTU" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_CURSO_FK" FOREIGN KEY ("CURSO_IDCURSO")
	  REFERENCES "TDIGITAL"."CURSO" ("IDCURSO") ON DELETE CASCADE ENABLE;
